name: Automerge from PR Event
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  merge:
    name: merge
    runs-on: ubuntu-18.04
    steps:
      - uses: k-kinzal/pr-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: merge cw-ozaki/aaa - 'state == `\"aaa\"`'
