name: Automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  merge:
    name: Summary
    runs-on: ubuntu-18.04
    steps:
      - uses: "k-kinzal/pr-action/check@dev"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NO_EXIT_CODE: true
        with:
          args: -l "user.login == `\"github-actions[bot]\"`"
