name: Automerge
on:
  pull_request:
    types:
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - opened
    - edited
    - reopened
    - synchronize
    - ready_for_review
    - review_requested
    - review_request_removed
  pull_request_review:
    types:
    - submitted
  pull_request_review_comment:
    types:
    - created
    - edited
  status: {}
jobs:
  merge:
    name: Summary
    runs-on: ubuntu-18.04
    steps:
      - uses: "k-kinzal/pr-action/check@dev"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NO_EXIT_CODE: true
        with:
          args: -l "user.login == `\"github-actions[bot]\"`"
