name: Automerge from PR Event
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  merge:
    name: merge
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set Value
        id: PR_NUMBER
        run: echo ::set-output name=tag::$(echo $GITHUB_REF | awk -F / '{print $3}')
      - uses: k-kinzal/pr-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: merge k-kinzal/pr-action -l 'number == `${{ steps.PR_NUMBER }}`' -l "state == `\"open\"`" -l "user.login == `\"github-actions[bot]\"`'
