name: Automerge from PR Event
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  merge:
    name: merge
    runs-on: ubuntu-18.04
    steps:
      - name: Env
        run: env
      - name: Payload
        run: cat $GITHUB_EVENT_PATH
      - name: Perflog
        run: cat /home/runner/perflog
      - name: Set Value
        id: set_pr_number
        run: echo ::set-output name=number::$(echo $GITHUB_REF | awk -F / '{print $3}')
      - uses: "k-kinzal/pr-action@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: -l "number == `${{ steps.set_pr_number.outputs.number }}`" -l "state == `\"open\"`" -l "user.login == `\"github-actions[bot]\"`"
